### ISSUE TITLE
Why the program gets stuck here?

### ISSUE THREAD

**Issue by zjq0455** [xuyuzhuang11/OneBit#1]
I try to train a model but it gets stuck here for several hours, what's wrong?
![1716387766006](https://github.com/xuyuzhuang11/OneBit/assets/150804715/59392742-7aaf-4624-bf9b-d973f960a10b)

**Comment by xuyuzhuang11** [comment]
It seems that there is no error here, could you please provide more information about this problem?

**Comment by zjq0455** [comment]
Thank you for answering! GPU communication error leads to the issue and I have fixed it.

**Comment by zjq0455** [comment]
> It seems that there is no error here, could you please provide more information about this problem?

Thank you for answering! GPU communication error leads to the issue and I have fixed it.

**Comment by xuyuzhuang11** [comment]
> > It seems that there is no error here, could you please provide more information about this problem?
> 
> Thank you for answering! GPU communication error leads to the issue and I have fixed it.

OK~

**Comment by JimmyCrave** [comment]
> > It seems that there is no error here, could you please provide more information about this problem?
> 
> Thank you for answering! GPU communication error leads to the issue and I have fixed it.

I encountered the same problem, how did you solve it?
