### ISSUE TITLE
STE Gradient

### ISSUE THREAD

**Issue by bg51717** [xuyuzhuang11/OneBit#10]
This is the code in the `transformers/src/transformers/models/bitnet.py`:
```
class SignSTEFunc(torch.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return torch.sign(input)

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        return grad_output * (1.001 - torch.tanh(input) ** 2)
        # return grad_output * (1.01 - torch.tanh(input) ** 2)
```
Why not directly propagate when calculating gradients, but instead use `grad_output * (1.001 - torch.tanh(input) ** 2)`?
Thanks for your reply.

**Comment by xuyuzhuang11** [comment]
Hi, this is the approximation of the derivative of Sign(`). The reason for we perform this is to smooth the training process. :-)
