### ISSUE TITLE
Error in installation instructions

### ISSUE THREAD

**Issue by dveloper77** [xuyuzhuang11/OneBit#2]
Hi there!

1. The requirement file resides in root folder, not in llama_factory.
2. An additionnal dot is required in the last command is this case (pip install -r ../requirements.txt)

Thx!

git clone https://github.com/xuyuzhuang11/OneBit.git
cd OneBit/transformers
pip install -e .
cd ../llama_factory
_pip install -r ./requirements.txt_

**Comment by xuyuzhuang11** [comment]
> Hi there!
> 
> 1. The requirement file resides in root folder, not in llama_factory.
> 2. An additionnal dot is required in the last command is this case (pip install -r ../requirements.txt)
> 
> Thx!
> 
> git clone https://github.com/xuyuzhuang11/OneBit.git cd OneBit/transformers pip install -e . cd ../llama_factory _pip install -r ./requirements.txt_

Thanks for your remind! This issue is settled.
