### ISSUE TITLE
Do you any plans to support Qwen2 72B?

### ISSUE THREAD

**Issue by lihuibng** [xuyuzhuang11/OneBit#4]
Do you any plans to support Qwen2 72B?

**Comment by xuyuzhuang11** [comment]
Hi, friends! For 72B model, we are very sorry now for lacking sufficient computational resources now. Once we have more GPU, these larger model will be considered. :-) Thanks for your attention!

**Comment by xuyuzhuang11** [comment]
If there is no comments, I will close this issue.
