### ISSUE TITLE
reproduce your code

### ISSUE THREAD

**Issue by hsb1995** [xuyuzhuang11/OneBit#5]
Your work is great and I have been following your progress regarding model compression.
I am reproducing your work and have the following problem with data issues:
![1718884943975](https://github.com/xuyuzhuang11/OneBit/assets/149936473/856354f3-14ea-40e9-9b73-25799b051096)

How does this data work, I finished downloading all_gen_132k.json as you said, but then you said generate data. I went to run generate_data again and it didn't run through, so I wanted to get your advice on how you use this data issue?

**Comment by xuyuzhuang11** [comment]
Hi! Thanks for your attention. I regret to face the GPU resource bottleneck from your environment. :-( But for data, they (data from my online-disk) have been generated from my work and released in my online-disk, and you can directly use them to reproduce our experiments. You need not to generate them again. I hope my reply can help you. Best wishes! :-)
