### ISSUE TITLE
could you provide opt1.3b.sh?

### ISSUE THREAD

**Issue by zxbjushuai** [xuyuzhuang11/OneBit#9]
I want to quantize llama2_7B but OOM.My cuda memory(48GB) is not enough for llama2_7B,so I want to try models that take up less memory

**Comment by xuyuzhuang11** [comment]
Only a few parameters are changed here in LLAMA-7B.sh, you should change the model path with your OPT-1.3B path!

**Comment by zxbjushuai** [comment]
oh,thank you very much!🤗
